version: '3'
services:
  ros2yolo-service:
    # build:
    #   context: ..
    #   dockerfile: .devcontainer/Dockerfile
    image: nagisa1201/commonimages:yolo-gpu
    container_name: yolo_container
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - OMP_WAIT_POLICY=passive
      - TERM=xterm-256color
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./..:/home/Nagisa/yolo
      - /dev:/dev
    network_mode: host
    pid: "host" # 添加 pid 命名空间共享
    ipc: "host" # 添加 ipc 命名空间共享    
    privileged: true
    stdin_open: true
    tty: true
    user: "Nagisa"
    runtime: "nvidia"
    working_dir: "/home/Nagisa/yolo" # 指定默认工作目录

